# Evaluation configs
method: B1_CG_fixed_smth0.01_obs0.1_maxscore
ol_alg: Baseline
goal_idx: -4  # >0: goal index in goal set, -1: closest, -2: minimum cost, -3: random, -4 max score
no_endpoint_smoothing: True 
chomp_adam: False
use_standoff: True
goal_set_proj: True
start_end_equal: True

use_goal_grad: True
use_min_cost_traj: False
pc: True
goal_thresh: 0.0001

allow_collision_point: 0
remove_flip_grasp: False

smoothness_base_weight: 0.01
base_obstacle_weight: 0.1

base_step_size: 0.03
optim_steps: 500 
pre_terminate: True
dist_func: control_points