# Evaluation configs
method: CG_IK_Fixed_nostandoff
ol_alg: Fixed
goal_idx: -1  # >0: goal index in goal set, -1: closest, -2: minimum cost, -3: random

use_standoff: False
use_goal_grad: True
use_min_cost_traj: False
filter_collision: False
smooth_loss_on_endpoint: False
start_end_equal: False # 
initial_ik: False
chomp_adam: True
# grasp_weights: /media/thomasweng/manifolds/clust_multirun/3obj_cpd_pc_rot/outdist_cpd-augrot/default_default_grasp-manifolds/50_50_2st6e01o/checkpoints/epoch=49-step=276100.ckpt
pc: True
goal_thresh: 0.0001

allow_collision_point: 0
goal_set_proj: False
remove_flip_grasp: False
smoothness_base_weight: 0.01
base_obstacle_weight: 0.1 
base_grasp_weight: 1.0
cost_schedule_boost: 1.0
base_step_size: 0.01
optim_steps: 500 
pre_terminate: True
dist_func: control_points
consider_finger: False