# Evaluation configs
method: GF_known_chmpadam
use_goal_grad: True
fixed_endpoint: False
ol_alg: null 
use_min_cost_traj: False
filter_collision: False
chomp_adam: True

goal_set_proj: False
remove_flip_grasp: False
smoothness_base_weight: 0.1
base_obstacle_weight: 0.7
base_grasp_weight: 5.0
cost_schedule_boost: 1.0
base_step_size: 0.3
optim_steps: 250
use_initial_ik: False
pre_terminate: True