# Evaluation configs
method: GF_known
use_goal_grad: True
ol_alg: null 
use_min_cost_traj: True
filter_collision: False
smooth_loss_on_endpoint: False
start_end_equal: True
initial_ik: False
chomp_adam: True

goal_set_proj: False
remove_flip_grasp: False
smoothness_base_weight: 0.01
base_obstacle_weight: 0.005
base_grasp_weight: 1.0
cost_schedule_boost: 1.0
base_step_size: 0.03
optim_steps: 250
pre_terminate: True