# Evaluation configs
method: GF_known_mincosttraj
use_goal_grad: True
ol_alg: null 
use_min_cost_traj: True
filter_collision: False
smooth_loss_on_endpoint: True
start_end_equal: True
initial_ik: False

goal_set_proj: False
remove_flip_grasp: False
smoothness_base_weight: 0.1
base_obstacle_weight: 0.7
base_grasp_weight: 5.0
cost_schedule_boost: 1.0
base_step_size: 0.3
optim_steps: 250
pre_terminate: True