# Evaluation configs
method: NGDF_intraBottle_grasp1k_smth0.01_obs0.1
no_endpoint_smoothing: True
use_standoff: False
use_goal_grad: True
ol_alg: null 
use_min_cost_traj: False
filter_collision: False
start_end_equal: True
initial_ik: True
chomp_adam: True
per_class_models: True
grasp_weights: 
  - Bottle:${data_root}/models/Bottle_intracategory_partial/default_default_train-graspfields/0_0_248dyj7f/checkpoints/epoch=0-step=199999.ckpt
pc: True
goal_thresh: 0.0000001

allow_collision_point: 0
goal_set_proj: False
remove_flip_grasp: False

smoothness_base_weight: 0.01
max_smooth_weight: 0.01
smooth_schedule_rate: 1.0

base_obstacle_weight: 0.001
max_obstacle_weight: 0.1
obs_schedule_rate: 1.01

base_grasp_weight: 1000.0
min_grasp_weight: 1000.0
grasp_schedule_rate: 1.0

base_step_size: 0.03
optim_steps: 500
extra_smooth_steps: 0
pre_terminate: True
dist_func: control_points