# Evaluation configs
method: GF_learned-perobj_softplusv2
use_standoff: False
use_goal_grad: True
ol_alg: null 
use_min_cost_traj: False
filter_collision: False
smooth_loss_on_endpoint: False
start_end_equal: True
initial_ik: False
chomp_adam: True
per_class_models: True
grasp_weights: 
  - Bottle:/media/thomasweng/manifolds/clust_multirun/softplus_v2/objBottle-actsoftplus-clampNone/default_default_train-graspfields/7_7_3cvjezlf/checkpoints/epoch=7-step=217544.ckpt
  - Bowl:/media/thomasweng/manifolds/clust_multirun/softplus_v2/objBowl-actsoftplus-clampNone/default_default_train-graspfields/7_7_nlwopzfi/checkpoints/epoch=8-step=231876.ckpt
  - Mug:/media/thomasweng/manifolds/clust_multirun/softplus_v2/objMug-actsoftplus-clampNone/default_default_train-graspfields/8_8_32eagewk/checkpoints/epoch=5-step=122386.ckpt
pc: True
goal_thresh: 0.0001

allow_collision_point: 0
goal_set_proj: False
remove_flip_grasp: False
smoothness_base_weight: 0.1
base_obstacle_weight: 1.0 
base_grasp_weight: 10.0
cost_schedule_boost: 1.0
base_step_size: 0.03
optim_steps: 500
pre_terminate: True
dist_func: control_points
consider_finger: False