# Evaluation configs
method: GF_learned-perobj_deepsdf_obs0.1_nofilt_ik_v1 # new models
no_endpoint_smoothing: True # False
# collision_point_num: 30  # collision point sample number for each link
use_standoff: False
use_goal_grad: True
ol_alg: null 
use_min_cost_traj: False
filter_collision: False
start_end_equal: True #
initial_ik: True
chomp_adam: True
per_class_models: True
grasp_weights: 
  - Bottle:/media/thomasweng/manifolds/clust_multirun/filt_vs_unfilt_v2/objBottle_unfilt/default_default_train-graspfields/7_7_afncqec4/checkpoints/epoch=11-step=330694.ckpt
  - Bowl:/media/thomasweng/manifolds/clust_multirun/filt_vs_unfilt_v2/objBowl_unfilt/default_default_train-graspfields/12_12_896ry9iw/checkpoints/epoch=16-step=436505.ckpt
  - Mug:/media/thomasweng/manifolds/clust_multirun/filt_vs_unfilt_v2/objMug_unfilt/default_default_train-graspfields/6_6_2hckgzjp/checkpoints/epoch=9-step=247474.ckpt
pc: True
goal_thresh: 0.0001

allow_collision_point: 0
goal_set_proj: False
remove_flip_grasp: False

smoothness_base_weight: 0.01
max_smooth_weight: 0.01

base_obstacle_weight: 0.001
max_obstacle_weight: 0.1
obs_schedule_rate: 1.01

base_grasp_weight: 1000.0
min_grasp_weight: 100.0
grasp_schedule_rate: 0.999

base_step_size: 0.03
optim_steps: 500
extra_smooth_steps: 0  # extra steps for postprocessing fixed goal
pre_terminate: True
dist_func: control_points
consider_finger: True