# Evaluation configs
method: GF_learned-perobj_deepsdf
no_endpoint_smoothing: True # False
use_standoff: False
use_goal_grad: True
ol_alg: null 
use_min_cost_traj: False
filter_collision: False
start_end_equal: True #
initial_ik: False
chomp_adam: True
per_class_models: True
grasp_weights: 
  - Bottle:/media/thomasweng/manifolds/clust_multirun/softplus_v2/objBottle-actsoftplus-clampNone/default_default_train-graspfields/14_14_3cvjezlf/checkpoints/epoch=12-step=351574.ckpt
  - Bowl:/media/thomasweng/manifolds/clust_multirun/softplus_v2/objBowl-actsoftplus-clampNone/default_default_train-graspfields/15_15_nlwopzfi/checkpoints/epoch=13-step=407967.ckpt
  - Mug:/media/thomasweng/manifolds/clust_multirun/softplus_v2/objMug-actsoftplus-clampNone/default_default_train-graspfields/11_11_32eagewk/checkpoints/epoch=11-step=301216.ckpt
pc: True
goal_thresh: 0.0001

allow_collision_point: 0
goal_set_proj: False
remove_flip_grasp: False

smoothness_base_weight: 0.01

base_obstacle_weight: 0.01
max_obstacle_weight: 1
obs_schedule_rate: 1.01

base_grasp_weight: 1000.0
min_grasp_weight: 100.0
grasp_schedule_rate: 0.999

base_step_size: 0.03
optim_steps: 500
extra_smooth_steps: 0  # extra steps for postprocessing fixed goal
pre_terminate: True
dist_func: control_points
consider_finger: True