data_root: /home/thomasweng/data/manifolds
experiment: dbg
dataset: acronym_mini_relabel

defaults:
  - eval: 1obj_float_rotpos_nograv
  - variant: origOMG_known_col

hydra:
  job:
    chdir: True
  run:
    dir: ${data_root}/pybullet_eval/${experiment}/${variant.method}_${now:%Y-%m-%d_%H%M%S}

# Evaluation configs
render: True
write_video: True
run_scenes: True # run full evaluation

# Other configs
vis: False
window_width: 200
window_height: 200 
 