###
# Overwrite these configs here or in the command
###
data_root: /path/to/ngdf/data
project_root: /path/to/ngdf/projects
experiment: dbg
dataset: dataset_name

defaults:
  - eval: 1obj_float_rotpos_nograv
  - variant: default

hydra:
  job:
    chdir: True
  sweep:
    dir: ${data_root}/pybullet_eval/multirun/${experiment}/${variant.method}_${now:%Y-%m-%d_%H%M%S}
    subdir: ${eval.eval_env}-${variant.method}-${hydra.job.num}
  run:
    dir: ${data_root}/pybullet_eval/${experiment}/${variant.method}_${now:%Y-%m-%d_%H%M%S}

# Evaluation configs
render: True
write_video: True
run_scenes: True 

# Other configs
vis: False
window_width: 200
window_height: 200 
 