# Evaluation configs
method: CG_IK_omg_nostandoff
ol_alg: MD
goal_idx: -1  # >0: goal index in goal set, -1: closest, -2: minimum cost, -3: random
no_endpoint_smoothing: True 
chomp_adam: False
use_standoff: True
goal_set_proj: True

use_goal_grad: True
use_min_cost_traj: False
# filter_collision: False
start_end_equal: False # 
# initial_ik: False
pc: True
goal_thresh: 0.0001

allow_collision_point: 0
remove_flip_grasp: False

smoothness_base_weight: 0.001
base_obstacle_weight: 0.01
# base_grasp_weight: 10.0

cost_schedule_boost: 1.0
base_step_size: 0.03
optim_steps: 500 
pre_terminate: True
dist_func: control_points
consider_finger: True