# Evaluation configs
method: GF_learned-perobj_deepsdf_obs0.1_ik_v2 # new models
no_endpoint_smoothing: True # False
# collision_point_num: 30  # collision point sample number for each link
use_standoff: False
use_goal_grad: True
ol_alg: null 
use_min_cost_traj: False
filter_collision: False
start_end_equal: True #
initial_ik: True
chomp_adam: True
per_class_models: True
grasp_weights: 
  - Bottle:/media/thomasweng/manifolds/clust_multirun/filt_vs_unfilt_v3/objBottle_filt/default_default_train-graspfields/1_1_1l4n000q/checkpoints/epoch=8-step=409584.ckpt
  - Bowl:/media/thomasweng/manifolds/clust_multirun/filt_vs_unfilt_v3/objBowl_filt/default_default_train-graspfields/2_2_h2wl9a8s/checkpoints/epoch=12-step=576405.ckpt
  - Mug:/media/thomasweng/manifolds/clust_multirun/filt_vs_unfilt_v3/objMug_filt/default_default_train-graspfields/1_1_1fam9ko7/checkpoints/epoch=10-step=511027.ckpt
pc: True
goal_thresh: 0.0000001

allow_collision_point: 0
goal_set_proj: False
remove_flip_grasp: False

smoothness_base_weight: 0.01
max_smooth_weight: 0.01

base_obstacle_weight: 0.001
max_obstacle_weight: 0.1
obs_schedule_rate: 1.01

base_grasp_weight: 1000.0
min_grasp_weight: 100.0
grasp_schedule_rate: 0.999

base_step_size: 0.03
optim_steps: 500
extra_smooth_steps: 0  # extra steps for postprocessing fixed goal
pre_terminate: True
dist_func: control_points
consider_finger: True