eval_env: panda_ycb_env
# eval_type: 1obj_float_rotpose_nograv
# obj_csv: data/object_rotations.csv
table: False
cam_look: 
  - -0.05
  - -0.5
  - -0.6852
tgt_pos: 
  - 0.5
  - 0.0
  - 0.5
gravity: False